FROM node:16-alpine

LABEL org.opencontainers.image.source=https://github.com/Dev-One-Project/ONF-client

WORKDIR /onf/
COPY ./package.json /onf/
# COPY ./yarn.lock /onf/
RUN yarn install --force --network-timeout 1000000

RUN apk add tzdata && ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

COPY . /onf/
CMD ["yarn", "dev"]