version: '3.7'

services:
  onf-client:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: onf-client
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Seoul
