export const styleSet = {
  colors: {
    white: '#fff',
    black: '#000',
    gray: '#ccc',
    darkGray: '#777',
    lightGray: '#eee',
    primary: '#e47e7e',
    subColor01: '#FA8F7D',
    subColor02: '#F09B78',
    subColor03: '#FA7DBB',
    subColor04: '#F078F0',
    subColor05: '#ffdddd',
    tp: 'transparent',
    fail: 'red',
    officeGo: '#1354d9',
    officeLateness: '#bf0920',
    officeNone: '#d27300',
    officeVacation: '#01853d',
  },
  fonts: {
    L: 'SCDream2',
    M: 'SCDream3',
    B: 'SCDream4',
    EB: 'SCDream5',
  },
  fontSizes: {
    big: '2.125rem',
    subTitle: '1.625rem',
    strong: '1.25rem',
    normal: '1rem',
    small: '0.8rem',
  },
  breakPoints: {
    mobile: '(max-width: 767px)',
    tablet: '(max-width: 1024px)',
  },
};
